src/apps/Hosting/HostingDialog.js
=> [DASH-2236] Set first Hosting Socket as default

src/apps/Hosting/HostingDialog.js
=> [DASH-2245] Fill Hosting Add/Edit dialog with useful content

src/apps/Channels/SendChannelMessageDialog.js, src/apps/Channels/SendChannelMessageDialogStore.js, src/apps/Syncano/Actions/Channels.js
- also clears message input with every message sent
=> [DASH-2187] Send channel messages with pressing enter

src/apps/DemoApps/DemoApp.js, src/apps/DemoApps/DemoAppBlogLink.js, src/apps/DemoApps/index.js
When the demo app hasn't any connected blog post, there is only link to github repository.
=> [DASH-2104] Adjust demo apps list

src/apps/Hosting/HostingList.js, src/apps/Hosting/HostingListItem.js, src/pages/maintenance.js
=> [DASH-2275] Fix Hosting list item not properly aligned

src/common/Header/Header.jsx
=> [DASH-2277] Move "getting started" to first position on top nav bar

src/apps/Hosting/Files.js, src/common/InnerToolbar/InnerToolbar.js
=> [DASH-2228] Add a Go Back button to hosting files tree view

src/common/Header/Header.jsx
=> [DASH-2277] Remove padding

src/apps/Hosting/Files.js, src/apps/Profile/ProfileBillingPlanReceiptDialog.jsx, src/apps/PushNotifications/PushNotificationsListItem.jsx, src/common/PricingPlans/PricingPlansPlan.js, test.sh, test/e2e/pages/billingPlanPage.js, test/e2e/pages/pushDevicesPage.js, test/e2e/pages/socketsPage.js, test/e2e/tests/billing/testPlansAndPricing.js, test/e2e/tests/notifications/testPushSocketsApns.js, test/setup/delete/instance.js
=> [DASH-2298] Add Hosting ID in InnerToolbar

src/apps/CustomSocketsRegistry/CustomSocketsRegistry.js, src/apps/CustomSocketsRegistry/CustomSocketsRegistryActions.js, src/apps/CustomSocketsRegistry/CustomSocketsRegistryList.js, src/apps/CustomSocketsRegistry/CustomSocketsRegistryListItem.js, src/apps/CustomSocketsRegistry/CustomSocketsRegistrySummary.js, src/apps/CustomSocketsRegistry/DetailsView/CustomSocketCodeExample.js, src/apps/CustomSocketsRegistry/DetailsView/CustomSocketDetailContentSection.js, src/apps/CustomSocketsRegistry/DetailsView/CustomSocketDetailsView.js, src/apps/CustomSocketsRegistry/SocketsRegistryInnerToolbar.js, src/apps/Scripts/BaseScripts.js, src/apps/Syncano/Actions/CustomSockets.js, src/apps/Syncano/Actions/CustomSocketsRegistry.js
And some minor eslint and style fixes
Screenshot with button fixed (no longer white points visible on buttons):
=> [DASH-2280] Fix curl code examples in CustomSocketCodeExample

package.json, src/apps/Hosting/DotsListItem.js, src/apps/Hosting/HostingDialog.js, src/apps/Hosting/HostingFilesList.js, src/apps/Hosting/HostingFilesListItem.js, src/apps/Hosting/HostingList.js, src/common/DirectoryNavigation/DirectoryNavigation.js, src/common/DirectoryNavigation/DirectoryNavigationLink.js, src/common/DirectoryNavigation/index.js, src/common/index.js
I have to look at this after a day to see if I like the styles.
=> [DASH-2323] Add navigation bar in hosting files view

src/apps/Scripts/BaseScripts.js, src/apps/Syncano/Actions/Scripts.js, src/common/Editor/Editor.jsx
=> [DASH-2302] Add PHP Sample Code

package.json
=> fix(package): update react-helmet to version 3.2.1

src/apps/Instances/InstanceDialog.jsx, src/common/Dialog/DialogStandardButtons.js, src/common/Header/InvitationItem.js
- also switched order of buttons in the notification:
=> [DASH-2356] Invited admin can 'delete' a shared instance

src/apps/BackupAndRestore/Full/FullBackupsActions.js
The problem was with Backup not DemoApps
=> [DASH-2364] User is not able to enter demo app

src/common/Header/Header.jsx
=> [DASH-2375] Remove solutions from the top menu

src/pages/instance.jsx
=> [DASH-2374] Remove subcategories from push notifications and push messages

src/apps/DataObjects/DataObjectDialog.jsx
=> [DASH-2399] Fix TypeError this.refs[(fieldtime- + e)].setTime 

src/apps/GlobalConfig/GlobalConfigDialog.js, test/e2e/pages/globalConfigPage.js, test/e2e/tests/settings/testGlobalConfig.js
- are we sure we really want to comment out all these changes?
- should I comment out actions too?
=> [DASH-2378] Change global config to readonly

src/pages/instance.jsx
And remove commented out code in `pages/instance.jsx`
=> [DASH-2401] Remove API Keys from left menu

src/apps/PushDevices/APNSDevices/APNSDevices.jsx, src/apps/PushDevices/AllDevicesLists.jsx, src/apps/PushDevices/GCMDevices/GCMDevices.jsx, src/apps/PushMessages/APNS/APNSMessagesList.js, src/apps/PushMessages/GCM/GCMMessagesList.js
url, add Helmet title on all devices list
=> [DASH-2393] Fix infinite loading when we go to all devices list by

package.json
Done as suggested in : http://stackoverflow.com/a/26438076/4872523
=> [DASH-2406] Change how tags are pushed when deploying master branch

package.json
=> fix(package): update material-ui to version 0.16.4

package.json
=> chore(package): update aws-sdk to version 2.7.4

src/apps/CustomSockets/CustomSockets.js, src/apps/CustomSockets/CustomSocketsActions.js, src/apps/CustomSockets/CustomSocketsEndpoints.js, src/apps/CustomSockets/CustomSocketsEndpointsActions.js, src/apps/CustomSockets/CustomSocketsEndpointsList.js, src/apps/CustomSockets/CustomSocketsEndpointsListItem.js, src/apps/CustomSockets/CustomSocketsEndpointsStore.js, src/apps/CustomSockets/CustomSocketsList.js, src/apps/CustomSockets/CustomSocketsListItem.js, src/apps/CustomSockets/CustomSocketsStore.js, src/apps/Syncano/Actions/CustomSockets.js, src/pages/instance.jsx, src/routes.jsx, src/utils/ActionsConstructor.js
Installed Sockets view:
Installed Sockets endpoints:
=> [SNG-DASH-2445]

src/apps/DataEndpoints/ClassSchemaTable.js
=> [DASH-2447] Remove the expand option for relation field type

src/common/EmptyView/EmptyViewDouble.js
=> [DASH-2451] Fix broken sock-et word.

src/apps/SocketsRegistry/DetailsView/SocketCodeExample.js, src/assets/index.html
=> [SNG-DASH-2279] Change theme of code snippets in Sockets Registry to dark one

src/apps/CustomSockets/CustomSockets.js, src/apps/CustomSockets/CustomSocketsEndpoints.js, src/apps/CustomSockets/CustomSocketsList.js, src/apps/CustomSockets/CustomSocketsListItem.js, src/apps/Instances/InstancesListItem.jsx, src/common/Header/HeaderInstancesDropdown.jsx, src/pages/instance.jsx, src/routes.jsx, src/utils/ActionsConstructor.js, src/utils/RoutesUtil.js
There's still an issue, when I want to change an instance multiple times from the instances list view.
It redirects correctly, but after 0.5 second it goes back to instances list, and don't let me go any further. Any idea what may cause the problem?
=> [DASH-2452] Redirect to my-sockets instead of sockets registry list

package.json, src/apps/SocketsRegistry/DetailsView/SocketDetailInfoBar.js
=> [DASH-2278] Fix sidebar styles, use proper react-tap-event-plugin

src/apps/Channels/ChannelsList.jsx, src/apps/DataObjects/DataObjectDialog.jsx, src/apps/DataObjects/DataObjectDialogStore.js, src/apps/DataObjects/DataObjectSearchForm.js, src/apps/DataObjects/DataObjects.jsx, src/apps/DataObjects/DataObjectsStore.js, src/apps/Sockets/Sockets.jsx, src/apps/Sockets/SocketsList.js, src/common/Dialog/DeleteDialog.jsx, src/common/Pagination/Pagination.js, test/e2e/globals.js, test/e2e/pages/channelsPage.js, test/e2e/pages/dataObjectsPage.js, test/e2e/pages/signupPage.js, test/e2e/pages/socketsPage.js, test/e2e/tests/billing/testPaymentMethods.js, test/e2e/tests/components/testDataObjects.js, test/e2e/tests/signup_logins/testSignup.js, test/e2e/tests/sockets/testChannels.js, yarn.lock
=> [DASH-2457] Add possibility for delete data object by ID

package.json
=> chore(package): update selenium-standalone to version 5.11.0

package.json
=> chore(package): update node-sass to version 4.4.0

README.md, circle.yml, test.sh
to reflect a new way of deployment
=> [SYN5-84-2] Change circle.yml and test.sh

src/assets/sass/_base.sass, src/common/BetaDialogContent/BetaDialogContent.js, src/common/BetaDialogContent/PromoteSyncanoSection.js, src/common/Dialog/BlurPageDialog.js, src/pages/dashboard.jsx
=> [SYN5-244] Implement referal page email input in the dashboard

src/apps/GlobalConfig/GlobalConfigDialog.js, test/e2e/pages/globalsViewerPage.js, test/e2e/tests/settings/testGlobalViewer.js
=> [SYN5-319] Change Global Config editor to simple displaying content

src/apps/Instances/InstancesListItem.jsx, src/common/Tooltip/Tooltip.js
=> [SYN5-300] Add "deprecated" info on old instances

src/apps/Instances/InstancesListItem.jsx, src/utils/RoutesUtil.js
=> [SYN5-449] Change maintenance to deprecated to mark old instances

src/apps/Instances/InstancesListItem.jsx, src/common/Tooltip/Tooltip.js, src/utils/RoutesUtil.js
=> [SYN5-449-old] Change maintenance to deprecated to mark old instances

src/common/Header/HeaderInstancesDropdown.jsx
=> [SYN5-455] Add deprecated info in the instances dropdown

src/common/Header/HeaderInstancesDropdown.jsx
=> [SYN5-455-old] Add deprecated info in the instances dropdown

circle.yml, src/apps/Session/SessionStore.js
=> [Release] 2017.04.27
